services:
  db:
    build:
      context: .
      dockerfile: dockerfile-db
    image: molinks-db
    command: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  web:
    build:
      context: .
      dockerfile: dockerfile-web-prod
    image: molinks-web
    command: uwsgi --ini /code/uwsgi.ini
    ports:
      - "8192:8192"
    environment:
      - POSTGRES_NAME=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - db

volumes:
    postgres-data:
