services:
  db:
    restart: "always"
    build:
      context: .
      dockerfile: dockerfile-db
    image: molinks-db
    command: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
      - secrets/env

  web:
    restart: "always"
    build:
      context: .
      dockerfile: dockerfile-web-prod
    image: molinks-web
    command: uwsgi --ini /project/uwsgi.ini
    ports:
      - "127.0.0.1:8000:8000"
    env_file:
      - .env
      - secrets/env
    depends_on:
      - db

volumes:
    postgres-data:

