services:
  db:
    restart: "always"

  web:
    restart: "always"
    command: uwsgi --ini /project/uwsgi.ini
    # Note: this does not replace the base env_file entry, it adds to it
    env_file: etc/secrets.env

