version: "3.7"

services:
  db:
    build:
      context: .
      dockerfile: dockerfile-db
    command: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=molinks
      - POSTGRES_USER=molinks
      - POSTGRES_PASSWORD=molinks-password
  web:
    build:
      context: .
      dockerfile: dockerfile-web
    command: bash -c "while true; do python manage.py runserver 0.0.0.0:8000; sleep 1; done"
    volumes:
      - .:/code
      - ./web-home:/home/stephenk
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=molinks
      - POSTGRES_USER=molinks
      - POSTGRES_PASSWORD=molinks-password
    depends_on:
      - db

volumes:
    postgres-data:
