services:
  db:
    build:
      context: .
      dockerfile: dockerfile-db
    image: molinks-db
    command: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file: .env

  web:
    build:
      context: .
      dockerfile: dockerfile-web-prod
    image: molinks-web
    command: sleep infinity
    ports:
      - "127.0.0.1:8000:8000"
    env_file: .env
    depends_on:
      - db

volumes:
    postgres-data:

