services:
  db:
    restart: "always"
    env_file:
      - etc/secrets.env

  web:
    restart: "always"
    command: uwsgi --ini /project/uwsgi.ini
    env_file:
      - etc/prod.env
      - etc/secrets.env

