version: "3.7"

services:
  db:
    image: postgres:14-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=molinks
      - POSTGRES_USER=molinks
      - POSTGRES_PASSWORD=molinks-password
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=molinks
      - POSTGRES_USER=molinks
      - POSTGRES_PASSWORD=molinks-password
    depends_on:
      - db

volumes:
    postgres-data:
